### ISSUE TITLE
Select with function strftime in where

### ISSUE THREAD

**Issue by RafaMunoz** [rest-go/rest#1]
Hi,

I have a sqlite table with a TEXT field called arrival_time.
This column can have values of hours greater than 24:00:00 that would indicate that they belong to a following day. 24:30:00 = 00:30:00 to the next day.

|arrival_time|
|--|
|23:02:21	|
|23:02:43|	
|23:03:19	|
|24:04:07|	
|24:04:58	|

The searches to stay with the rows greater than 24:00:00 I do with the following query (with sqlite studio):
`SELECT * FROM nombre_tabla WHERE strftime('%s', arrival_time) > strftime('%s', '24:00:00');`

Is there a way to do it through the GET method with your Docker container?

Thanks!!

**Comment by shellfly** [comment]
@RafaMunoz `strftime` is not supported now, but you should be able to use `gt` for this case:
I created an example table named `bill`, and it works
```
curl  "localhost:3000/bill?arrival_time=gt.24:00:00"
[{"arrival_time":"24:04:07"}]
```

**Comment by RafaMunoz** [comment]
Hi,

Thank you very much for testing, but I have bad news, those operators are not valid, I have already been testing.
At first it seems to work but when you use it in conjunction with "lt" you realize that something strange is happening.

The operators "<" and ">" are comparison operators used to compare numeric values. When used with text strings, these operators compare the values of character codes in the ASCII or Unicode table, which can produce unexpected or incorrect results.

I also have two other questions that I have not seen and it is very possible that it is not implemented but I ask just in case.

- Do you have view support? I have done some test but it has not worked for me, it is possible that I am doing something wrong.

-  Is there a way to limit the methods it supports (GET, POST) via environment variable or otherwise?


Thanks!

**Comment by RafaMunoz** [comment]
Currently I have the test view that contains the following query and running it manually with `select * from test` works correctly:

`select * from stop_times where arrival_time > "24:00:00" and arrival_time > "24:01:00";`

![image](https://user-images.githubusercontent.com/12030658/233093935-7b959086-b723-4800-a3a0-673e42156501.png)

![image](https://user-images.githubusercontent.com/12030658/233094166-17d0d3bc-02f2-4473-9919-3d6af4d55745.png)


When I call it from the web I get the following response:
```
http://localhost:3000/test
{"msg": "table does not exist: test"}
```

**Comment by shellfly** [comment]
@RafaMunoz I just merged a MR to support sqlite view, you should be able to use it in the latest version now, you can install the latest version and have a try.

**Comment by RafaMunoz** [comment]
Hi,

Thanks, now i can see the views :)
