### ISSUE TITLE
SQL syntax error with Authentication POST requests

### ISSUE THREAD

**Issue by kadattack** [rest-go/rest#11]
**Describe the bug**
Every POST request that uses the rest-go built in Authentication returns a SQL parse error:

> {"msg":"failed to exec sql, ERROR: syntax error at or near \"2\" (SQLSTATE 42601)"}

 The GET, DELETE, PUT requests for fetch, delete and update work with out issue.

**To Reproduce**
* Set up Authentication & Authorization as provided by [https://rest-go.com/docs/guides/auth](https://rest-go.com/docs/guides/auth)
* add user to auth_policies with
| 4  | use userid | test_table      | all         | 2 = auth\_user\.id  |

* Create table and fill it with data:
```
CREATE TABLE test_table (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER NOT NULL
);
INSERT INTO test_table (name, value)
VALUES
    ('Alice', 10),
    ('Bob', 20),
    ('Charlie', 30),
    ('Diana', 40),
    ('Eve', 50);
```

* write a curl request 
`curl -XPOST 192.168.122.31:3000/test_table  -H "Authorization: Bearer $TOKEN"  -d '{"name": "Test", "age": 20}'`

**Expected behavior**
It should insert a new row in to the table.

**Environment if applicable (please complete the following information):**
 - OS: ubuntu 22.04

**Additional context**
* This only happens when you combine the `-XPOST -H "Authorization: Bearer $TOKEN"  -d '{}'` together.
If authorization is not required it works without issues. 
* Adding `-H "Content-Type: application/json"`  provides no difference.

**Comment by padeny** [comment]
Thanks for your feedback. In fact, it is not a bug but rather an incorrect usage of `auth_policies`. 
Specifically, in this part: 
`| 4 | use userid | test_table | all | 2 = auth_user.id |`, the `2 = auth_user.id` should not be written like this. The value `2` is supposed to correspond to a column in the table. 

In the guides where user_id = auth_user.id is used, it means the query is selecting rows from the table where the user_id matches the currently logged-in user. For this to work, the table must include a user_id column.

If you want authenticated users to be able to operate on `test_table`, the expression can simply be written as `auth_user.is_authenticated`, like:  4 | use userid | test_table | all | auth_user.is_authenticated|.

We will improve the guides later to explain this issue.
