### ISSUE TITLE
Modified Version

### ISSUE THREAD

**Issue by SOG-web** [rest-go/rest#12]
Hi I made a modified version of this project to support surrealQl and also remove the http layer (this allowed me to use the package as just a sql query generator from http request)

I hope this is fine by you, I have added the right attribution to this repo

**Comment by shellfly** [comment]
@SOG-web Welcome to fork and modify based on your requirements, please keep the same license for unmodified code and have a notice about what's changed to align the current license for this repo.

**Comment by SOG-web** [comment]
Ok, great Thanks
