### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by py-radicz** [rest-go/rest#4]
is there a way I can overcome CORS (any option I can set CORS headers) restriction when I am running api and api consumer code on same machine but different ports? thanks in advance

**Comment by YogiLiu** [comment]
Hi @shellfly! Is this feature ready for production? Has any plan to release new version?

**Comment by shellfly** [comment]
@YogiLiu I'll make a new release, does the #5 solve your requirement? I see you create another PR

**Comment by YogiLiu** [comment]
@shellfly #5 only solve the issue about cors when auth-disabled, I try to fix another issue, wait a minute.

**Comment by shellfly** [comment]
@YogiLiu OK, can you update your PR using https://github.com/rs/cors? it's a more standard way to do it.
