### ISSUE TITLE
missing operator to select datetime range

### ISSUE THREAD

**Issue by serveryang** [rest-go/rest#8]
if have a `create_at` coloum in table, how to filtering using `gte` and `lte`  operator to select by range.

**Comment by serveryang** [comment]
I have read the document, can't find `logic operator` to implement filter `create_at`  column in range. 
sql statement like
`
select * from tablename where create_at >= '2020-10-10 12:12:12' and create_at <= '2024-10-10 12:12:12'
`
multi create_at in querystring of api will ignore first one.

**Comment by shellfly** [comment]
@serveryang it's supported now, you can try the latest master to use it.
